package com.maskmanage.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.maskmanage.entity.donation;
import com.maskmanage.entity.donationExample;

public interface donationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int countByExample(donationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int deleteByExample(donationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int deleteByPrimaryKey(Integer donationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int insert(donation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int insertSelective(donation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    List<donation> selectByExample(donationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    donation selectByPrimaryKey(Integer donationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") donation record, @Param("example") donationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByExample(@Param("record") donation record, @Param("example") donationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByPrimaryKeySelective(donation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByPrimaryKey(donation record);
}