package com.maskmanage.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.maskmanage.entity.hospital;
import com.maskmanage.entity.hospitalExample;

public interface hospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int countByExample(hospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int deleteByExample(hospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int deleteByPrimaryKey(Integer hosid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int insert(hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int insertSelective(hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    List<hospital> selectByExample(hospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    hospital selectByPrimaryKey(Integer hosid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") hospital record, @Param("example") hospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByExample(@Param("record") hospital record, @Param("example") hospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByPrimaryKeySelective(hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByPrimaryKey(hospital record);
}