package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.maskmanage.entity.hossupervision;
import com.maskmanage.entity.hossupervisionExample;

public interface hossupervisionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hossupervision
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int countByExample(hossupervisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hossupervision
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int deleteByExample(hossupervisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hossupervision
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int deleteByPrimaryKey(Integer supervisionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hossupervision
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int insert(hossupervision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hossupervision
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int insertSelective(hossupervision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hossupervision
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    List<hossupervision> selectByExample(hossupervisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hossupervision
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    hossupervision selectByPrimaryKey(Integer supervisionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hossupervision
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") hossupervision record, @Param("example") hossupervisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hossupervision
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByExample(@Param("record") hossupervision record, @Param("example") hossupervisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hossupervision
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByPrimaryKeySelective(hossupervision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hossupervision
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    int updateByPrimaryKey(hossupervision record);
}