package com.maskmanage.entity;

import java.util.ArrayList;
import java.util.List;

public class adminExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public adminExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdminidIsNull() {
            addCriterion("adminId is null");
            return (Criteria) this;
        }

        public Criteria andAdminidIsNotNull() {
            addCriterion("adminId is not null");
            return (Criteria) this;
        }

        public Criteria andAdminidEqualTo(Integer value) {
            addCriterion("adminId =", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotEqualTo(Integer value) {
            addCriterion("adminId <>", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThan(Integer value) {
            addCriterion("adminId >", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThanOrEqualTo(Integer value) {
            addCriterion("adminId >=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThan(Integer value) {
            addCriterion("adminId <", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThanOrEqualTo(Integer value) {
            addCriterion("adminId <=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidIn(List<Integer> values) {
            addCriterion("adminId in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotIn(List<Integer> values) {
            addCriterion("adminId not in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidBetween(Integer value1, Integer value2) {
            addCriterion("adminId between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotBetween(Integer value1, Integer value2) {
            addCriterion("adminId not between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminuseridIsNull() {
            addCriterion("adminUserId is null");
            return (Criteria) this;
        }

        public Criteria andAdminuseridIsNotNull() {
            addCriterion("adminUserId is not null");
            return (Criteria) this;
        }

        public Criteria andAdminuseridEqualTo(Integer value) {
            addCriterion("adminUserId =", value, "adminuserid");
            return (Criteria) this;
        }

        public Criteria andAdminuseridNotEqualTo(Integer value) {
            addCriterion("adminUserId <>", value, "adminuserid");
            return (Criteria) this;
        }

        public Criteria andAdminuseridGreaterThan(Integer value) {
            addCriterion("adminUserId >", value, "adminuserid");
            return (Criteria) this;
        }

        public Criteria andAdminuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("adminUserId >=", value, "adminuserid");
            return (Criteria) this;
        }

        public Criteria andAdminuseridLessThan(Integer value) {
            addCriterion("adminUserId <", value, "adminuserid");
            return (Criteria) this;
        }

        public Criteria andAdminuseridLessThanOrEqualTo(Integer value) {
            addCriterion("adminUserId <=", value, "adminuserid");
            return (Criteria) this;
        }

        public Criteria andAdminuseridIn(List<Integer> values) {
            addCriterion("adminUserId in", values, "adminuserid");
            return (Criteria) this;
        }

        public Criteria andAdminuseridNotIn(List<Integer> values) {
            addCriterion("adminUserId not in", values, "adminuserid");
            return (Criteria) this;
        }

        public Criteria andAdminuseridBetween(Integer value1, Integer value2) {
            addCriterion("adminUserId between", value1, value2, "adminuserid");
            return (Criteria) this;
        }

        public Criteria andAdminuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("adminUserId not between", value1, value2, "adminuserid");
            return (Criteria) this;
        }

        public Criteria andAdminstatusIsNull() {
            addCriterion("adminStatus is null");
            return (Criteria) this;
        }

        public Criteria andAdminstatusIsNotNull() {
            addCriterion("adminStatus is not null");
            return (Criteria) this;
        }

        public Criteria andAdminstatusEqualTo(String value) {
            addCriterion("adminStatus =", value, "adminstatus");
            return (Criteria) this;
        }

        public Criteria andAdminstatusNotEqualTo(String value) {
            addCriterion("adminStatus <>", value, "adminstatus");
            return (Criteria) this;
        }

        public Criteria andAdminstatusGreaterThan(String value) {
            addCriterion("adminStatus >", value, "adminstatus");
            return (Criteria) this;
        }

        public Criteria andAdminstatusGreaterThanOrEqualTo(String value) {
            addCriterion("adminStatus >=", value, "adminstatus");
            return (Criteria) this;
        }

        public Criteria andAdminstatusLessThan(String value) {
            addCriterion("adminStatus <", value, "adminstatus");
            return (Criteria) this;
        }

        public Criteria andAdminstatusLessThanOrEqualTo(String value) {
            addCriterion("adminStatus <=", value, "adminstatus");
            return (Criteria) this;
        }

        public Criteria andAdminstatusLike(String value) {
            addCriterion("adminStatus like", value, "adminstatus");
            return (Criteria) this;
        }

        public Criteria andAdminstatusNotLike(String value) {
            addCriterion("adminStatus not like", value, "adminstatus");
            return (Criteria) this;
        }

        public Criteria andAdminstatusIn(List<String> values) {
            addCriterion("adminStatus in", values, "adminstatus");
            return (Criteria) this;
        }

        public Criteria andAdminstatusNotIn(List<String> values) {
            addCriterion("adminStatus not in", values, "adminstatus");
            return (Criteria) this;
        }

        public Criteria andAdminstatusBetween(String value1, String value2) {
            addCriterion("adminStatus between", value1, value2, "adminstatus");
            return (Criteria) this;
        }

        public Criteria andAdminstatusNotBetween(String value1, String value2) {
            addCriterion("adminStatus not between", value1, value2, "adminstatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin
     *
     * @mbggenerated do_not_delete_during_merge Wed May 27 13:01:29 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}