package com.maskmanage.entity;

public class admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer adminuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminStatus
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String adminstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminId
     *
     * @return the value of admin.adminId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminId
     *
     * @param adminid the value for admin.adminId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminUserId
     *
     * @return the value of admin.adminUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getAdminuserid() {
        return adminuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminUserId
     *
     * @param adminuserid the value for admin.adminUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setAdminuserid(Integer adminuserid) {
        this.adminuserid = adminuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminStatus
     *
     * @return the value of admin.adminStatus
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getAdminstatus() {
        return adminstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminStatus
     *
     * @param adminstatus the value for admin.adminStatus
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setAdminstatus(String adminstatus) {
        this.adminstatus = adminstatus;
    }
}