package com.maskmanage.entity;

import java.util.Date;

public class column {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column.columnId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer columnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column.columnTitle
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String columntitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column.author
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column.columnAdminId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer columnadminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column.columnContent
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String columncontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column.columnInterviewee
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String columninterviewee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column.columnPubTime
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Date columnpubtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column.columnId
     *
     * @return the value of column.columnId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getColumnid() {
        return columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column.columnId
     *
     * @param columnid the value for column.columnId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setColumnid(Integer columnid) {
        this.columnid = columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column.columnTitle
     *
     * @return the value of column.columnTitle
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getColumntitle() {
        return columntitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column.columnTitle
     *
     * @param columntitle the value for column.columnTitle
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setColumntitle(String columntitle) {
        this.columntitle = columntitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column.author
     *
     * @return the value of column.author
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column.author
     *
     * @param author the value for column.author
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column.columnAdminId
     *
     * @return the value of column.columnAdminId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getColumnadminid() {
        return columnadminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column.columnAdminId
     *
     * @param columnadminid the value for column.columnAdminId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setColumnadminid(Integer columnadminid) {
        this.columnadminid = columnadminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column.columnContent
     *
     * @return the value of column.columnContent
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getColumncontent() {
        return columncontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column.columnContent
     *
     * @param columncontent the value for column.columnContent
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setColumncontent(String columncontent) {
        this.columncontent = columncontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column.columnInterviewee
     *
     * @return the value of column.columnInterviewee
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getColumninterviewee() {
        return columninterviewee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column.columnInterviewee
     *
     * @param columninterviewee the value for column.columnInterviewee
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setColumninterviewee(String columninterviewee) {
        this.columninterviewee = columninterviewee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column.columnPubTime
     *
     * @return the value of column.columnPubTime
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Date getColumnpubtime() {
        return columnpubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column.columnPubTime
     *
     * @param columnpubtime the value for column.columnPubTime
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setColumnpubtime(Date columnpubtime) {
        this.columnpubtime = columnpubtime;
    }
}