package com.maskmanage.entity;

import java.util.Date;

public class data {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.dataId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer dataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.dataTitle
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String datatitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.dataLocation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String datalocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.dataAdminId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer dataadminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.dataPubTime
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Date datapubtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.dataId
     *
     * @return the value of data.dataId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getDataid() {
        return dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.dataId
     *
     * @param dataid the value for data.dataId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDataid(Integer dataid) {
        this.dataid = dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.dataTitle
     *
     * @return the value of data.dataTitle
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getDatatitle() {
        return datatitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.dataTitle
     *
     * @param datatitle the value for data.dataTitle
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDatatitle(String datatitle) {
        this.datatitle = datatitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.dataLocation
     *
     * @return the value of data.dataLocation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getDatalocation() {
        return datalocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.dataLocation
     *
     * @param datalocation the value for data.dataLocation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDatalocation(String datalocation) {
        this.datalocation = datalocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.dataAdminId
     *
     * @return the value of data.dataAdminId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getDataadminid() {
        return dataadminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.dataAdminId
     *
     * @param dataadminid the value for data.dataAdminId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDataadminid(Integer dataadminid) {
        this.dataadminid = dataadminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.dataPubTime
     *
     * @return the value of data.dataPubTime
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Date getDatapubtime() {
        return datapubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.dataPubTime
     *
     * @param datapubtime the value for data.dataPubTime
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDatapubtime(Date datapubtime) {
        this.datapubtime = datapubtime;
    }
}