package com.maskmanage.entity;

import java.util.Date;

public class donator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donator.donatorId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer donatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donator.donatorName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String donatorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donator.donatorTel
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String donatortel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donator.donatorUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer donatoruserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donator.donatorSignDate
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Date donatorsigndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donator.donatorIDnum
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String donatoridnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donator.donatorId
     *
     * @return the value of donator.donatorId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getDonatorid() {
        return donatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donator.donatorId
     *
     * @param donatorid the value for donator.donatorId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDonatorid(Integer donatorid) {
        this.donatorid = donatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donator.donatorName
     *
     * @return the value of donator.donatorName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getDonatorname() {
        return donatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donator.donatorName
     *
     * @param donatorname the value for donator.donatorName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDonatorname(String donatorname) {
        this.donatorname = donatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donator.donatorTel
     *
     * @return the value of donator.donatorTel
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getDonatortel() {
        return donatortel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donator.donatorTel
     *
     * @param donatortel the value for donator.donatorTel
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDonatortel(String donatortel) {
        this.donatortel = donatortel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donator.donatorUserId
     *
     * @return the value of donator.donatorUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getDonatoruserid() {
        return donatoruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donator.donatorUserId
     *
     * @param donatoruserid the value for donator.donatorUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDonatoruserid(Integer donatoruserid) {
        this.donatoruserid = donatoruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donator.donatorSignDate
     *
     * @return the value of donator.donatorSignDate
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Date getDonatorsigndate() {
        return donatorsigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donator.donatorSignDate
     *
     * @param donatorsigndate the value for donator.donatorSignDate
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDonatorsigndate(Date donatorsigndate) {
        this.donatorsigndate = donatorsigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donator.donatorIDnum
     *
     * @return the value of donator.donatorIDnum
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getDonatoridnum() {
        return donatoridnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donator.donatorIDnum
     *
     * @param donatoridnum the value for donator.donatorIDnum
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDonatoridnum(String donatoridnum) {
        this.donatoridnum = donatoridnum;
    }
}