package com.maskmanage.entity;

public class donsupervision {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donsupervision.supervisionId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer supervisionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donsupervision.supId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer supid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donsupervision.donId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer donid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donsupervision.status
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donsupervision.supervisionId
     *
     * @return the value of donsupervision.supervisionId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getSupervisionid() {
        return supervisionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donsupervision.supervisionId
     *
     * @param supervisionid the value for donsupervision.supervisionId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setSupervisionid(Integer supervisionid) {
        this.supervisionid = supervisionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donsupervision.supId
     *
     * @return the value of donsupervision.supId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getSupid() {
        return supid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donsupervision.supId
     *
     * @param supid the value for donsupervision.supId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setSupid(Integer supid) {
        this.supid = supid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donsupervision.donId
     *
     * @return the value of donsupervision.donId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getDonid() {
        return donid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donsupervision.donId
     *
     * @param donid the value for donsupervision.donId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDonid(Integer donid) {
        this.donid = donid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donsupervision.status
     *
     * @return the value of donsupervision.status
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donsupervision.status
     *
     * @param status the value for donsupervision.status
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}