package com.maskmanage.entity;

import java.util.Date;

public class hospital {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hosId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer hosid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hosLocation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String hoslocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hosName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String hosname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hosUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer hosuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hosTel
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String hostel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hosSignDate
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Date hossigndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hosIDnum
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String hosidnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hosId
     *
     * @return the value of hospital.hosId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getHosid() {
        return hosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hosId
     *
     * @param hosid the value for hospital.hosId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setHosid(Integer hosid) {
        this.hosid = hosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hosLocation
     *
     * @return the value of hospital.hosLocation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getHoslocation() {
        return hoslocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hosLocation
     *
     * @param hoslocation the value for hospital.hosLocation
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setHoslocation(String hoslocation) {
        this.hoslocation = hoslocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hosName
     *
     * @return the value of hospital.hosName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getHosname() {
        return hosname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hosName
     *
     * @param hosname the value for hospital.hosName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setHosname(String hosname) {
        this.hosname = hosname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hosUserId
     *
     * @return the value of hospital.hosUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getHosuserid() {
        return hosuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hosUserId
     *
     * @param hosuserid the value for hospital.hosUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setHosuserid(Integer hosuserid) {
        this.hosuserid = hosuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hosTel
     *
     * @return the value of hospital.hosTel
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getHostel() {
        return hostel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hosTel
     *
     * @param hostel the value for hospital.hosTel
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setHostel(String hostel) {
        this.hostel = hostel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hosSignDate
     *
     * @return the value of hospital.hosSignDate
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Date getHossigndate() {
        return hossigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hosSignDate
     *
     * @param hossigndate the value for hospital.hosSignDate
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setHossigndate(Date hossigndate) {
        this.hossigndate = hossigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hosIDnum
     *
     * @return the value of hospital.hosIDnum
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getHosidnum() {
        return hosidnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hosIDnum
     *
     * @param hosidnum the value for hospital.hosIDnum
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setHosidnum(String hosidnum) {
        this.hosidnum = hosidnum;
    }
}