package com.maskmanage.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class hospitalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public hospitalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHosidIsNull() {
            addCriterion("hosId is null");
            return (Criteria) this;
        }

        public Criteria andHosidIsNotNull() {
            addCriterion("hosId is not null");
            return (Criteria) this;
        }

        public Criteria andHosidEqualTo(Integer value) {
            addCriterion("hosId =", value, "hosid");
            return (Criteria) this;
        }

        public Criteria andHosidNotEqualTo(Integer value) {
            addCriterion("hosId <>", value, "hosid");
            return (Criteria) this;
        }

        public Criteria andHosidGreaterThan(Integer value) {
            addCriterion("hosId >", value, "hosid");
            return (Criteria) this;
        }

        public Criteria andHosidGreaterThanOrEqualTo(Integer value) {
            addCriterion("hosId >=", value, "hosid");
            return (Criteria) this;
        }

        public Criteria andHosidLessThan(Integer value) {
            addCriterion("hosId <", value, "hosid");
            return (Criteria) this;
        }

        public Criteria andHosidLessThanOrEqualTo(Integer value) {
            addCriterion("hosId <=", value, "hosid");
            return (Criteria) this;
        }

        public Criteria andHosidIn(List<Integer> values) {
            addCriterion("hosId in", values, "hosid");
            return (Criteria) this;
        }

        public Criteria andHosidNotIn(List<Integer> values) {
            addCriterion("hosId not in", values, "hosid");
            return (Criteria) this;
        }

        public Criteria andHosidBetween(Integer value1, Integer value2) {
            addCriterion("hosId between", value1, value2, "hosid");
            return (Criteria) this;
        }

        public Criteria andHosidNotBetween(Integer value1, Integer value2) {
            addCriterion("hosId not between", value1, value2, "hosid");
            return (Criteria) this;
        }

        public Criteria andHoslocationIsNull() {
            addCriterion("hosLocation is null");
            return (Criteria) this;
        }

        public Criteria andHoslocationIsNotNull() {
            addCriterion("hosLocation is not null");
            return (Criteria) this;
        }

        public Criteria andHoslocationEqualTo(String value) {
            addCriterion("hosLocation =", value, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHoslocationNotEqualTo(String value) {
            addCriterion("hosLocation <>", value, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHoslocationGreaterThan(String value) {
            addCriterion("hosLocation >", value, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHoslocationGreaterThanOrEqualTo(String value) {
            addCriterion("hosLocation >=", value, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHoslocationLessThan(String value) {
            addCriterion("hosLocation <", value, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHoslocationLessThanOrEqualTo(String value) {
            addCriterion("hosLocation <=", value, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHoslocationLike(String value) {
            addCriterion("hosLocation like", value, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHoslocationNotLike(String value) {
            addCriterion("hosLocation not like", value, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHoslocationIn(List<String> values) {
            addCriterion("hosLocation in", values, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHoslocationNotIn(List<String> values) {
            addCriterion("hosLocation not in", values, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHoslocationBetween(String value1, String value2) {
            addCriterion("hosLocation between", value1, value2, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHoslocationNotBetween(String value1, String value2) {
            addCriterion("hosLocation not between", value1, value2, "hoslocation");
            return (Criteria) this;
        }

        public Criteria andHosnameIsNull() {
            addCriterion("hosName is null");
            return (Criteria) this;
        }

        public Criteria andHosnameIsNotNull() {
            addCriterion("hosName is not null");
            return (Criteria) this;
        }

        public Criteria andHosnameEqualTo(String value) {
            addCriterion("hosName =", value, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosnameNotEqualTo(String value) {
            addCriterion("hosName <>", value, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosnameGreaterThan(String value) {
            addCriterion("hosName >", value, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosnameGreaterThanOrEqualTo(String value) {
            addCriterion("hosName >=", value, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosnameLessThan(String value) {
            addCriterion("hosName <", value, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosnameLessThanOrEqualTo(String value) {
            addCriterion("hosName <=", value, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosnameLike(String value) {
            addCriterion("hosName like", value, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosnameNotLike(String value) {
            addCriterion("hosName not like", value, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosnameIn(List<String> values) {
            addCriterion("hosName in", values, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosnameNotIn(List<String> values) {
            addCriterion("hosName not in", values, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosnameBetween(String value1, String value2) {
            addCriterion("hosName between", value1, value2, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosnameNotBetween(String value1, String value2) {
            addCriterion("hosName not between", value1, value2, "hosname");
            return (Criteria) this;
        }

        public Criteria andHosuseridIsNull() {
            addCriterion("hosUserId is null");
            return (Criteria) this;
        }

        public Criteria andHosuseridIsNotNull() {
            addCriterion("hosUserId is not null");
            return (Criteria) this;
        }

        public Criteria andHosuseridEqualTo(Integer value) {
            addCriterion("hosUserId =", value, "hosuserid");
            return (Criteria) this;
        }

        public Criteria andHosuseridNotEqualTo(Integer value) {
            addCriterion("hosUserId <>", value, "hosuserid");
            return (Criteria) this;
        }

        public Criteria andHosuseridGreaterThan(Integer value) {
            addCriterion("hosUserId >", value, "hosuserid");
            return (Criteria) this;
        }

        public Criteria andHosuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("hosUserId >=", value, "hosuserid");
            return (Criteria) this;
        }

        public Criteria andHosuseridLessThan(Integer value) {
            addCriterion("hosUserId <", value, "hosuserid");
            return (Criteria) this;
        }

        public Criteria andHosuseridLessThanOrEqualTo(Integer value) {
            addCriterion("hosUserId <=", value, "hosuserid");
            return (Criteria) this;
        }

        public Criteria andHosuseridIn(List<Integer> values) {
            addCriterion("hosUserId in", values, "hosuserid");
            return (Criteria) this;
        }

        public Criteria andHosuseridNotIn(List<Integer> values) {
            addCriterion("hosUserId not in", values, "hosuserid");
            return (Criteria) this;
        }

        public Criteria andHosuseridBetween(Integer value1, Integer value2) {
            addCriterion("hosUserId between", value1, value2, "hosuserid");
            return (Criteria) this;
        }

        public Criteria andHosuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("hosUserId not between", value1, value2, "hosuserid");
            return (Criteria) this;
        }

        public Criteria andHostelIsNull() {
            addCriterion("hosTel is null");
            return (Criteria) this;
        }

        public Criteria andHostelIsNotNull() {
            addCriterion("hosTel is not null");
            return (Criteria) this;
        }

        public Criteria andHostelEqualTo(String value) {
            addCriterion("hosTel =", value, "hostel");
            return (Criteria) this;
        }

        public Criteria andHostelNotEqualTo(String value) {
            addCriterion("hosTel <>", value, "hostel");
            return (Criteria) this;
        }

        public Criteria andHostelGreaterThan(String value) {
            addCriterion("hosTel >", value, "hostel");
            return (Criteria) this;
        }

        public Criteria andHostelGreaterThanOrEqualTo(String value) {
            addCriterion("hosTel >=", value, "hostel");
            return (Criteria) this;
        }

        public Criteria andHostelLessThan(String value) {
            addCriterion("hosTel <", value, "hostel");
            return (Criteria) this;
        }

        public Criteria andHostelLessThanOrEqualTo(String value) {
            addCriterion("hosTel <=", value, "hostel");
            return (Criteria) this;
        }

        public Criteria andHostelLike(String value) {
            addCriterion("hosTel like", value, "hostel");
            return (Criteria) this;
        }

        public Criteria andHostelNotLike(String value) {
            addCriterion("hosTel not like", value, "hostel");
            return (Criteria) this;
        }

        public Criteria andHostelIn(List<String> values) {
            addCriterion("hosTel in", values, "hostel");
            return (Criteria) this;
        }

        public Criteria andHostelNotIn(List<String> values) {
            addCriterion("hosTel not in", values, "hostel");
            return (Criteria) this;
        }

        public Criteria andHostelBetween(String value1, String value2) {
            addCriterion("hosTel between", value1, value2, "hostel");
            return (Criteria) this;
        }

        public Criteria andHostelNotBetween(String value1, String value2) {
            addCriterion("hosTel not between", value1, value2, "hostel");
            return (Criteria) this;
        }

        public Criteria andHossigndateIsNull() {
            addCriterion("hosSignDate is null");
            return (Criteria) this;
        }

        public Criteria andHossigndateIsNotNull() {
            addCriterion("hosSignDate is not null");
            return (Criteria) this;
        }

        public Criteria andHossigndateEqualTo(Date value) {
            addCriterion("hosSignDate =", value, "hossigndate");
            return (Criteria) this;
        }

        public Criteria andHossigndateNotEqualTo(Date value) {
            addCriterion("hosSignDate <>", value, "hossigndate");
            return (Criteria) this;
        }

        public Criteria andHossigndateGreaterThan(Date value) {
            addCriterion("hosSignDate >", value, "hossigndate");
            return (Criteria) this;
        }

        public Criteria andHossigndateGreaterThanOrEqualTo(Date value) {
            addCriterion("hosSignDate >=", value, "hossigndate");
            return (Criteria) this;
        }

        public Criteria andHossigndateLessThan(Date value) {
            addCriterion("hosSignDate <", value, "hossigndate");
            return (Criteria) this;
        }

        public Criteria andHossigndateLessThanOrEqualTo(Date value) {
            addCriterion("hosSignDate <=", value, "hossigndate");
            return (Criteria) this;
        }

        public Criteria andHossigndateIn(List<Date> values) {
            addCriterion("hosSignDate in", values, "hossigndate");
            return (Criteria) this;
        }

        public Criteria andHossigndateNotIn(List<Date> values) {
            addCriterion("hosSignDate not in", values, "hossigndate");
            return (Criteria) this;
        }

        public Criteria andHossigndateBetween(Date value1, Date value2) {
            addCriterion("hosSignDate between", value1, value2, "hossigndate");
            return (Criteria) this;
        }

        public Criteria andHossigndateNotBetween(Date value1, Date value2) {
            addCriterion("hosSignDate not between", value1, value2, "hossigndate");
            return (Criteria) this;
        }

        public Criteria andHosidnumIsNull() {
            addCriterion("hosIDnum is null");
            return (Criteria) this;
        }

        public Criteria andHosidnumIsNotNull() {
            addCriterion("hosIDnum is not null");
            return (Criteria) this;
        }

        public Criteria andHosidnumEqualTo(String value) {
            addCriterion("hosIDnum =", value, "hosidnum");
            return (Criteria) this;
        }

        public Criteria andHosidnumNotEqualTo(String value) {
            addCriterion("hosIDnum <>", value, "hosidnum");
            return (Criteria) this;
        }

        public Criteria andHosidnumGreaterThan(String value) {
            addCriterion("hosIDnum >", value, "hosidnum");
            return (Criteria) this;
        }

        public Criteria andHosidnumGreaterThanOrEqualTo(String value) {
            addCriterion("hosIDnum >=", value, "hosidnum");
            return (Criteria) this;
        }

        public Criteria andHosidnumLessThan(String value) {
            addCriterion("hosIDnum <", value, "hosidnum");
            return (Criteria) this;
        }

        public Criteria andHosidnumLessThanOrEqualTo(String value) {
            addCriterion("hosIDnum <=", value, "hosidnum");
            return (Criteria) this;
        }

        public Criteria andHosidnumLike(String value) {
            addCriterion("hosIDnum like", value, "hosidnum");
            return (Criteria) this;
        }

        public Criteria andHosidnumNotLike(String value) {
            addCriterion("hosIDnum not like", value, "hosidnum");
            return (Criteria) this;
        }

        public Criteria andHosidnumIn(List<String> values) {
            addCriterion("hosIDnum in", values, "hosidnum");
            return (Criteria) this;
        }

        public Criteria andHosidnumNotIn(List<String> values) {
            addCriterion("hosIDnum not in", values, "hosidnum");
            return (Criteria) this;
        }

        public Criteria andHosidnumBetween(String value1, String value2) {
            addCriterion("hosIDnum between", value1, value2, "hosidnum");
            return (Criteria) this;
        }

        public Criteria andHosidnumNotBetween(String value1, String value2) {
            addCriterion("hosIDnum not between", value1, value2, "hosidnum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hospital
     *
     * @mbggenerated do_not_delete_during_merge Wed May 27 13:01:29 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hospital
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}