package com.maskmanage.entity;

public class hossupervision {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hossupervision.supervisionId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer supervisionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hossupervision.supId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer supid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hossupervision.hosId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer hosid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hossupervision.supervisionId
     *
     * @return the value of hossupervision.supervisionId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getSupervisionid() {
        return supervisionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hossupervision.supervisionId
     *
     * @param supervisionid the value for hossupervision.supervisionId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setSupervisionid(Integer supervisionid) {
        this.supervisionid = supervisionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hossupervision.supId
     *
     * @return the value of hossupervision.supId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getSupid() {
        return supid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hossupervision.supId
     *
     * @param supid the value for hossupervision.supId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setSupid(Integer supid) {
        this.supid = supid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hossupervision.hosId
     *
     * @return the value of hossupervision.hosId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getHosid() {
        return hosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hossupervision.hosId
     *
     * @param hosid the value for hossupervision.hosId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setHosid(Integer hosid) {
        this.hosid = hosid;
    }
}