package com.maskmanage.entity;

import java.util.Date;

public class requirement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqrId
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    private Integer reqrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqrName
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    private String reqrname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.type
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqrTime
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    private Date reqrtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqrStatus
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    private Integer reqrstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqrHosId
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    private Integer reqrhosid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.status
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqrId
     *
     * @return the value of requirement.reqrId
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public Integer getReqrid() {
        return reqrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqrId
     *
     * @param reqrid the value for requirement.reqrId
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public void setReqrid(Integer reqrid) {
        this.reqrid = reqrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqrName
     *
     * @return the value of requirement.reqrName
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public String getReqrname() {
        return reqrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqrName
     *
     * @param reqrname the value for requirement.reqrName
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public void setReqrname(String reqrname) {
        this.reqrname = reqrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.type
     *
     * @return the value of requirement.type
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.type
     *
     * @param type the value for requirement.type
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqrTime
     *
     * @return the value of requirement.reqrTime
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public Date getReqrtime() {
        return reqrtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqrTime
     *
     * @param reqrtime the value for requirement.reqrTime
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public void setReqrtime(Date reqrtime) {
        this.reqrtime = reqrtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqrStatus
     *
     * @return the value of requirement.reqrStatus
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public Integer getReqrstatus() {
        return reqrstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqrStatus
     *
     * @param reqrstatus the value for requirement.reqrStatus
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public void setReqrstatus(Integer reqrstatus) {
        this.reqrstatus = reqrstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqrHosId
     *
     * @return the value of requirement.reqrHosId
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public Integer getReqrhosid() {
        return reqrhosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqrHosId
     *
     * @param reqrhosid the value for requirement.reqrHosId
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public void setReqrhosid(Integer reqrhosid) {
        this.reqrhosid = reqrhosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.status
     *
     * @return the value of requirement.status
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.status
     *
     * @param status the value for requirement.status
     *
     * @mbggenerated Thu May 28 20:59:57 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }
}