package com.maskmanage.entity;

public class resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer resid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String resname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resId
     *
     * @return the value of resource.resId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resId
     *
     * @param resid the value for resource.resId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setResid(Integer resid) {
        this.resid = resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resName
     *
     * @return the value of resource.resName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getResname() {
        return resname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resName
     *
     * @param resname the value for resource.resName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setResname(String resname) {
        this.resname = resname;
    }
}