package com.maskmanage.entity;

import java.util.ArrayList;
import java.util.List;

public class supervisorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public supervisorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSupidIsNull() {
            addCriterion("supId is null");
            return (Criteria) this;
        }

        public Criteria andSupidIsNotNull() {
            addCriterion("supId is not null");
            return (Criteria) this;
        }

        public Criteria andSupidEqualTo(Integer value) {
            addCriterion("supId =", value, "supid");
            return (Criteria) this;
        }

        public Criteria andSupidNotEqualTo(Integer value) {
            addCriterion("supId <>", value, "supid");
            return (Criteria) this;
        }

        public Criteria andSupidGreaterThan(Integer value) {
            addCriterion("supId >", value, "supid");
            return (Criteria) this;
        }

        public Criteria andSupidGreaterThanOrEqualTo(Integer value) {
            addCriterion("supId >=", value, "supid");
            return (Criteria) this;
        }

        public Criteria andSupidLessThan(Integer value) {
            addCriterion("supId <", value, "supid");
            return (Criteria) this;
        }

        public Criteria andSupidLessThanOrEqualTo(Integer value) {
            addCriterion("supId <=", value, "supid");
            return (Criteria) this;
        }

        public Criteria andSupidIn(List<Integer> values) {
            addCriterion("supId in", values, "supid");
            return (Criteria) this;
        }

        public Criteria andSupidNotIn(List<Integer> values) {
            addCriterion("supId not in", values, "supid");
            return (Criteria) this;
        }

        public Criteria andSupidBetween(Integer value1, Integer value2) {
            addCriterion("supId between", value1, value2, "supid");
            return (Criteria) this;
        }

        public Criteria andSupidNotBetween(Integer value1, Integer value2) {
            addCriterion("supId not between", value1, value2, "supid");
            return (Criteria) this;
        }

        public Criteria andSupnameIsNull() {
            addCriterion("supName is null");
            return (Criteria) this;
        }

        public Criteria andSupnameIsNotNull() {
            addCriterion("supName is not null");
            return (Criteria) this;
        }

        public Criteria andSupnameEqualTo(String value) {
            addCriterion("supName =", value, "supname");
            return (Criteria) this;
        }

        public Criteria andSupnameNotEqualTo(String value) {
            addCriterion("supName <>", value, "supname");
            return (Criteria) this;
        }

        public Criteria andSupnameGreaterThan(String value) {
            addCriterion("supName >", value, "supname");
            return (Criteria) this;
        }

        public Criteria andSupnameGreaterThanOrEqualTo(String value) {
            addCriterion("supName >=", value, "supname");
            return (Criteria) this;
        }

        public Criteria andSupnameLessThan(String value) {
            addCriterion("supName <", value, "supname");
            return (Criteria) this;
        }

        public Criteria andSupnameLessThanOrEqualTo(String value) {
            addCriterion("supName <=", value, "supname");
            return (Criteria) this;
        }

        public Criteria andSupnameLike(String value) {
            addCriterion("supName like", value, "supname");
            return (Criteria) this;
        }

        public Criteria andSupnameNotLike(String value) {
            addCriterion("supName not like", value, "supname");
            return (Criteria) this;
        }

        public Criteria andSupnameIn(List<String> values) {
            addCriterion("supName in", values, "supname");
            return (Criteria) this;
        }

        public Criteria andSupnameNotIn(List<String> values) {
            addCriterion("supName not in", values, "supname");
            return (Criteria) this;
        }

        public Criteria andSupnameBetween(String value1, String value2) {
            addCriterion("supName between", value1, value2, "supname");
            return (Criteria) this;
        }

        public Criteria andSupnameNotBetween(String value1, String value2) {
            addCriterion("supName not between", value1, value2, "supname");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionIsNull() {
            addCriterion("supSubjection is null");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionIsNotNull() {
            addCriterion("supSubjection is not null");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionEqualTo(String value) {
            addCriterion("supSubjection =", value, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionNotEqualTo(String value) {
            addCriterion("supSubjection <>", value, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionGreaterThan(String value) {
            addCriterion("supSubjection >", value, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionGreaterThanOrEqualTo(String value) {
            addCriterion("supSubjection >=", value, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionLessThan(String value) {
            addCriterion("supSubjection <", value, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionLessThanOrEqualTo(String value) {
            addCriterion("supSubjection <=", value, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionLike(String value) {
            addCriterion("supSubjection like", value, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionNotLike(String value) {
            addCriterion("supSubjection not like", value, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionIn(List<String> values) {
            addCriterion("supSubjection in", values, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionNotIn(List<String> values) {
            addCriterion("supSubjection not in", values, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionBetween(String value1, String value2) {
            addCriterion("supSubjection between", value1, value2, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupsubjectionNotBetween(String value1, String value2) {
            addCriterion("supSubjection not between", value1, value2, "supsubjection");
            return (Criteria) this;
        }

        public Criteria andSupidnumIsNull() {
            addCriterion("supIDnum is null");
            return (Criteria) this;
        }

        public Criteria andSupidnumIsNotNull() {
            addCriterion("supIDnum is not null");
            return (Criteria) this;
        }

        public Criteria andSupidnumEqualTo(String value) {
            addCriterion("supIDnum =", value, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupidnumNotEqualTo(String value) {
            addCriterion("supIDnum <>", value, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupidnumGreaterThan(String value) {
            addCriterion("supIDnum >", value, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupidnumGreaterThanOrEqualTo(String value) {
            addCriterion("supIDnum >=", value, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupidnumLessThan(String value) {
            addCriterion("supIDnum <", value, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupidnumLessThanOrEqualTo(String value) {
            addCriterion("supIDnum <=", value, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupidnumLike(String value) {
            addCriterion("supIDnum like", value, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupidnumNotLike(String value) {
            addCriterion("supIDnum not like", value, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupidnumIn(List<String> values) {
            addCriterion("supIDnum in", values, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupidnumNotIn(List<String> values) {
            addCriterion("supIDnum not in", values, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupidnumBetween(String value1, String value2) {
            addCriterion("supIDnum between", value1, value2, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupidnumNotBetween(String value1, String value2) {
            addCriterion("supIDnum not between", value1, value2, "supidnum");
            return (Criteria) this;
        }

        public Criteria andSupuseridIsNull() {
            addCriterion("supUserId is null");
            return (Criteria) this;
        }

        public Criteria andSupuseridIsNotNull() {
            addCriterion("supUserId is not null");
            return (Criteria) this;
        }

        public Criteria andSupuseridEqualTo(Integer value) {
            addCriterion("supUserId =", value, "supuserid");
            return (Criteria) this;
        }

        public Criteria andSupuseridNotEqualTo(Integer value) {
            addCriterion("supUserId <>", value, "supuserid");
            return (Criteria) this;
        }

        public Criteria andSupuseridGreaterThan(Integer value) {
            addCriterion("supUserId >", value, "supuserid");
            return (Criteria) this;
        }

        public Criteria andSupuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("supUserId >=", value, "supuserid");
            return (Criteria) this;
        }

        public Criteria andSupuseridLessThan(Integer value) {
            addCriterion("supUserId <", value, "supuserid");
            return (Criteria) this;
        }

        public Criteria andSupuseridLessThanOrEqualTo(Integer value) {
            addCriterion("supUserId <=", value, "supuserid");
            return (Criteria) this;
        }

        public Criteria andSupuseridIn(List<Integer> values) {
            addCriterion("supUserId in", values, "supuserid");
            return (Criteria) this;
        }

        public Criteria andSupuseridNotIn(List<Integer> values) {
            addCriterion("supUserId not in", values, "supuserid");
            return (Criteria) this;
        }

        public Criteria andSupuseridBetween(Integer value1, Integer value2) {
            addCriterion("supUserId between", value1, value2, "supuserid");
            return (Criteria) this;
        }

        public Criteria andSupuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("supUserId not between", value1, value2, "supuserid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supervisor
     *
     * @mbggenerated do_not_delete_during_merge Wed May 27 13:01:29 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supervisor
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}