package com.maskmanage.entity;

public class supervisor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervisor.supId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer supid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervisor.supName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String supname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervisor.supSubjection
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String supsubjection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervisor.supIDnum
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String supidnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervisor.supUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer supuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervisor.supId
     *
     * @return the value of supervisor.supId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getSupid() {
        return supid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervisor.supId
     *
     * @param supid the value for supervisor.supId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setSupid(Integer supid) {
        this.supid = supid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervisor.supName
     *
     * @return the value of supervisor.supName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getSupname() {
        return supname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervisor.supName
     *
     * @param supname the value for supervisor.supName
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setSupname(String supname) {
        this.supname = supname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervisor.supSubjection
     *
     * @return the value of supervisor.supSubjection
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getSupsubjection() {
        return supsubjection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervisor.supSubjection
     *
     * @param supsubjection the value for supervisor.supSubjection
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setSupsubjection(String supsubjection) {
        this.supsubjection = supsubjection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervisor.supIDnum
     *
     * @return the value of supervisor.supIDnum
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getSupidnum() {
        return supidnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervisor.supIDnum
     *
     * @param supidnum the value for supervisor.supIDnum
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setSupidnum(String supidnum) {
        this.supidnum = supidnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervisor.supUserId
     *
     * @return the value of supervisor.supUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getSupuserid() {
        return supuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervisor.supUserId
     *
     * @param supuserid the value for supervisor.supUserId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setSupuserid(Integer supuserid) {
        this.supuserid = supuserid;
    }
}