package com.maskmanage.entity;

public class usage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usage.usageId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer usageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usage.usageTitle
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String usagetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usage.reqrId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer reqrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usage.usageDesc
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private String usagedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usage.check
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer check;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usage.usageHosId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    private Integer usagehosid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usage.usageId
     *
     * @return the value of usage.usageId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getUsageid() {
        return usageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usage.usageId
     *
     * @param usageid the value for usage.usageId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setUsageid(Integer usageid) {
        this.usageid = usageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usage.usageTitle
     *
     * @return the value of usage.usageTitle
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getUsagetitle() {
        return usagetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usage.usageTitle
     *
     * @param usagetitle the value for usage.usageTitle
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setUsagetitle(String usagetitle) {
        this.usagetitle = usagetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usage.reqrId
     *
     * @return the value of usage.reqrId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getReqrid() {
        return reqrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usage.reqrId
     *
     * @param reqrid the value for usage.reqrId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setReqrid(Integer reqrid) {
        this.reqrid = reqrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usage.usageDesc
     *
     * @return the value of usage.usageDesc
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public String getUsagedesc() {
        return usagedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usage.usageDesc
     *
     * @param usagedesc the value for usage.usageDesc
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setUsagedesc(String usagedesc) {
        this.usagedesc = usagedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usage.check
     *
     * @return the value of usage.check
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getCheck() {
        return check;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usage.check
     *
     * @param check the value for usage.check
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setCheck(Integer check) {
        this.check = check;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usage.usageHosId
     *
     * @return the value of usage.usageHosId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public Integer getUsagehosid() {
        return usagehosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usage.usageHosId
     *
     * @param usagehosid the value for usage.usageHosId
     *
     * @mbggenerated Wed May 27 13:01:29 CST 2020
     */
    public void setUsagehosid(Integer usagehosid) {
        this.usagehosid = usagehosid;
    }
}